language: node_js
node_js:
- 'node'
before_install:
- rvm install 2.2.2
before_script:
- gem install awesome_bot
script:
# `test` target executes `bundle exec rspec spec` and `npm run test`
# in all appropriate subdirectories
- make test
- awesome_bot README.md --white-list apple.com/fonts,medium.engineering,awesome.re